// Generates src/styles/tokens.css from the token sources in src/tokens/*.
// Run via `npm run tokens` after changing TYPE_BASE_PX / TYPE_RATIO or any
// color/spacing value — this file is the only thing that should ever write
// to tokens.css by hand.

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { buildTypeScale, TYPE_BASE_PX, TYPE_RATIO } from '../src/tokens/type-scale.ts'
import { MOOD_COLORS, BRAND_COLORS } from '../src/tokens/colors.ts'

const scale = buildTypeScale()

const fontSizeLines = scale
  .map(({ name, rem }) => `  --text-${name}: ${rem}rem;`)
  .join('\n')

const moodLines = Object.entries(MOOD_COLORS)
  .map(([name, hex]) => `  --color-mood-${name}: ${hex};`)
  .join('\n')

const brandLines = Object.entries(BRAND_COLORS)
  .map(([name, hex]) => `  --color-brand-${name}: ${hex};`)
  .join('\n')

const css = `/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand.
   Source of truth: src/tokens/type-scale.ts, src/tokens/colors.ts
   Current type scale: base ${TYPE_BASE_PX}px, ratio ${TYPE_RATIO} */

@theme {
${fontSizeLines}

${moodLines}

${brandLines}
}
`

const outPath = fileURLToPath(new URL('../src/styles/tokens.css', import.meta.url))
writeFileSync(outPath, css)

console.log(`tokens.css written (base ${TYPE_BASE_PX}px, ratio ${TYPE_RATIO}):`)
for (const { name, px, rem } of scale) {
  console.log(`  --text-${name.padEnd(4)} ${String(px).padStart(6)}px  (${rem}rem)`)
}
